name: Build Windows Executable
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build executable with PyInstaller
        uses: JackMcKew/pyinstaller-action-windows@v0.1.2
        with:
          path: '.'
          spec: 'k2c.spec' # 可选
         # requirements: 'requirements.txt' # 可选
      - run: ls dist
      - run: mv dist/k2c.exe .
      - name: zip the build
        run: |
          zip -r k2c.zip k2c.exe
          ls .
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v5
        env:
            GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          body: ${{steps.github_release.outputs.changelog}}
          files: |
            ./k2c.zip
